import assert from 'node:assert/strict';
import { coachGuides } from './coach-content.js';
import { problems } from './problems.js';
import { newAttempt, gradeAnswer, validRecords, summarizeProgress } from './practice-state.js';
import { newCoachState, answerCoachCheck, nextCoachCheck, answerSimilar, retrySimilar, answerReflection } from './coaching-state.js';

assert.deepEqual(Object.keys(coachGuides),Object.keys(problems));
const adaptationIds = new Set();
for (const [id,g] of Object.entries(coachGuides)) {
  assert.equal(g.checks.length,2);
  assert.ok(g.intro);
  for (const check of [...g.checks,g.similar.reflection]) {
    assert.equal(check.options.length,2);
    assert.equal(new Set(check.options.map((option) => option.id)).size,2);
    assert.equal(check.options.filter((option) => option.correct === true).length,1);
    assert.ok(check.options.every((option) => typeof option.correct === 'boolean' && option.feedback.length > 20));
  }
  assert.equal(g.similar.sourceProblem,id);
  assert.equal(g.similar.sourceUrl,problems[id].sourceUrl);
  assert.match(g.similar.label,/not an official AMC question/);
  assert.equal(g.similar.options.length,2);
  assert.ok(g.similar.options.some((option) => option.value === g.similar.answer));
  assert.ok(!Object.hasOwn(problems,g.similar.id));
  adaptationIds.add(g.similar.id);
  const state = newCoachState(), other = newCoachState();
  assert.throws(() => answerCoachCheck(g,state,g.checks[0].options[0].id),/Open/);
  state.open = true;
  assert.throws(() => nextCoachCheck(g,state),/Choose/);
  assert.throws(() => answerCoachCheck(g,state,'invalid'),/Choose/);
  const wrong = g.checks[0].options.find((option) => !option.correct);
  assert.equal(answerCoachCheck(g,state,wrong.id).correct,false);
  assert.throws(() => answerCoachCheck(g,state,g.checks[0].options.find((option) => option.correct).id),/already/);
  assert.equal(state.answers[0].correct,false,'A second choice cannot erase a first wrong response');
  assert.equal(other.answers.length,0,'Coaching stays local to each question');
  nextCoachCheck(g,state);
  const correct = g.checks[1].options.find((option) => option.correct);
  assert.equal(answerCoachCheck(g,state,correct.id).correct,true);
  assert.throws(() => nextCoachCheck(g,state),/no more/);
  assert.throws(() => answerSimilar(g,state,g.similar.answer),/Open/);
  state.similarOpen = true;
  assert.throws(() => answerReflection(g,state,g.similar.reflection.options[0].id),/Try/);
  assert.throws(() => answerSimilar(g,state,'invalid'),/Choose/);
  const wrongSimilar = g.similar.options.find((option) => option.value !== g.similar.answer);
  const result = answerSimilar(g,state,wrongSimilar.value);
  assert.equal(result.correct,false);
  assert.equal(result.independent,false);
  assert.equal(result.firstTry,true);
  assert.throws(() => answerSimilar(g,state,g.similar.answer),/already/);
  const reflection = g.similar.reflection.options.find((option) => option.correct);
  assert.equal(answerReflection(g,state,reflection.id).correct,true);
  assert.throws(() => answerReflection(g,state,reflection.id),/already/);
  retrySimilar(state);
  assert.equal(state.similarAnswer,null);
  assert.equal(state.similarSeen,true);
  const retry = answerSimilar(g,state,g.similar.answer);
  assert.equal(retry.correct,true);
  assert.equal(retry.independent,false,'Seeing a solution before retry is not fresh independent evidence');
  assert.equal(retry.firstTry,false);
  assert.equal(answerReflection(g,state,reflection.id).firstTry,false);
}
assert.equal(adaptationIds.size,4);
const expression = coachGuides['2026-1'].similar.expression;
const terms = expression.replaceAll('−','-').replaceAll(' ','').match(/[+-]?\d+/g).map(Number);
assert.equal(terms.length,12);
assert.equal(terms.reduce((sum,value) => sum + value,0),22);
assert.equal(coachGuides['2026-1'].similar.answer,22);
const matrix = coachGuides['2026-2'].similar.matrix;
assert.deepEqual(matrix.map((row) => row.length),[7,7,7,7,7]);
assert.deepEqual([2,3,4].map((n) => matrix.flat().filter((value) => value === n).length),[20,12,3]);
assert.equal(matrix.flat().reduce((sum,value) => sum+value,0),88);
assert.equal(coachGuides['2026-2'].similar.answer,88);
assert.deepEqual([6*6,4*Math.sqrt(100),9+12+Math.hypot(9,12)],[36,40,36]);
assert.equal(coachGuides['2026-3'].similar.answer,'A');
const percentPractice = coachGuides['2026-4'].similar;
assert.match(percentPractice.prompt,/25%/);
assert.match(percentPractice.prompt,/20%/);
assert.equal((100 - 25) + (100 - 25) / 5,90);
assert.equal(percentPractice.answer,90);
assert.deepEqual(percentPractice.options.map((option) => option.value),[95,90]);
const attempt = newAttempt();
attempt.coached = true;
assert.equal(gradeAnswer(problems['2026-1'],attempt,18).independent,false);
const untouched = newAttempt();
assert.equal(gradeAnswer(problems['2026-2'],untouched,53).independent,true);
const saved = validRecords([{problem:'2026-1',result:'coach',hints:0,independent:false,coached:true,at:'2026-09-27T00:00:00Z'}],problems);
assert.equal(saved.length,1);
assert.equal(summarizeProgress(saved).independent,0);
console.log('Verified coaching: eight binary checks, four checked adaptations, reflection feedback, gated state, duplicate protection, retries, and assisted original grading.');
