// Uses isolated synthetic browser storage only. No real learner records or network.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { JSDOM } from 'jsdom';
import { learningStorageKeys as keys } from './learning-store.js';
import { coachGuides } from './coach-content.js';

const html = fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const legacy = {problem:'2026-1',result:'correct',hints:0,independent:true,at:'2026-09-14T00:00:00Z'};
let scenario = 0;
async function setup(saved = {}, url = 'https://kmantec.github.io/AMC-Tutorial/?preview=1') {
  const dom = new JSDOM(html,{url,pretendToBeVisual:true});
  const w = dom.window, registrations = new Map(), errors = [], timers = [];
  w.addEventListener('error',(event) => { errors.push(event.error || event.message); event.preventDefault(); });
  w.HTMLElement.prototype.scrollIntoView = function() {};
  w.scrollTo = () => {};
  w.HTMLDialogElement.prototype.showModal = function() { this.open = true; };
  w.HTMLDialogElement.prototype.close = function() { this.open = false; this.dispatchEvent(new w.Event('close')); };
  for (const [key,value] of Object.entries(saved)) w.localStorage.setItem(key,value);
  const writes = [], set = w.Storage.prototype.setItem;
  w.Storage.prototype.setItem = function(key,value) { writes.push([key,value]); return set.call(this,key,value); };
  w.document.modelContext = {registerTool(tool) { registrations.set(tool.name,tool); }};
  Object.assign(globalThis,{window:w,document:w.document,location:w.location,history:w.history,FormData:w.FormData});
  const realSetTimeout = globalThis.setTimeout;
  globalThis.setTimeout = (fn,delay,...args) => { const id = realSetTimeout(fn,delay,...args); timers.push(id); return id; };
  await import('./app.js?uiScenario=' + (++scenario));
  const q = (selector) => { const result = w.document.querySelector(selector); assert.ok(result,'Missing element: ' + selector); return result; };
  const click = (selector) => { q(selector).click(); assert.deepEqual(errors,[]); };
  const read = () => registrations.get('read_practice_progress').execute();
  const open = (id) => registrations.get('start_practice_problem').execute({problemId:id});
  const answer = (value) => registrations.get('submit_practice_answer').execute({answer:value});
  const similar = (value) => {
    const radio = q('#similar-options input[value="' + value + '"]');
    radio.checked = true; radio.dispatchEvent(new w.Event('change',{bubbles:true}));
    q('#similar-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
    assert.deepEqual(errors,[]);
  };
  return {w,q,click,read,open,answer,similar,writes,registrations,
    snapshot:() => Object.fromEntries(Object.keys(w.localStorage).map((key) => [key,w.localStorage.getItem(key)])),
    close:() => { for (const id of timers) clearTimeout(id); globalThis.setTimeout = realSetTimeout; dom.window.close(); }};
}
const ui = await setup({[keys.original]:JSON.stringify([legacy]),[keys.mode]:'learning',unrelated:'keep'});
assert.equal(ui.read().mode,'preview');
assert.deepEqual(ui.read().records,[]);
assert.equal(ui.writes.length,0);
ui.open('2026-1');
assert.equal(ui.q('#coach-check').hidden,true,'No targeted coaching before a request');
assert.equal(ui.q('#similar-entry').hidden,true);
assert.equal(ui.q('#coach-options').children.length,0);
ui.answer(21);
ui.click('#coach-open');
assert.equal(ui.read().coachUsed,true);
assert.equal(ui.q('#coach-options').children.length,2);
const first = coachGuides['2026-1'].checks[0];
ui.click('[data-coach-answer="' + first.options.find((option) => !option.correct).id + '"]');
const length = ui.read().coachingRecords.length;
ui.click('[data-coach-answer="' + first.options.find((option) => option.correct).id + '"]');
assert.equal(ui.read().coachingRecords.length,length,'Disabled choices do not overwrite the first response');
assert.equal(ui.read().coachingRecords.at(-1).correct,false);
ui.click('#coach-next');
ui.click('[data-coach-answer="a"]');
ui.q('#practice-dialog').close();
ui.open('2026-2');
assert.equal(ui.q('#coach-check').hidden,true);
assert.equal(ui.q('#suggested-pace').textContent,'Suggested pace: within 1 min 30 sec');
assert.equal(ui.answer(53).independent,true,'Q1 assistance does not affect Q2');
const beforeVideo = ui.read().records.length;
ui.click('#video-button');
ui.click('#video-recommendations button');
assert.ok(ui.w.document.querySelector('#video-player iframe'));
assert.equal(ui.read().records.length,beforeVideo,'Post-answer video does not change the completed result');
ui.open('2026-1');
assert.equal(ui.w.document.querySelector('#video-player iframe'),null);
assert.equal(ui.q('#coach-check').hidden,false);
assert.match(ui.q('#coach-step').textContent,/2 OF 2/);
assert.equal(ui.answer(18).independent,false);
const originals = ui.read().records.length;
ui.click('#similar-open');
assert.equal(ui.q('#similar-options').querySelectorAll('input').length,2);
assert.equal(ui.q('#similar-explanation').hidden,true);
assert.equal(ui.q('#reflection-options').children.length,0);
ui.similar(26);
assert.equal(ui.read().records.length,originals,'Adapted results do not count as AMC attempts');
assert.equal(ui.read().coachingRecords.at(-1).kind,'similar');
assert.equal(ui.read().coachingRecords.at(-1).correct,false);
assert.equal(ui.q('#similar-explanation').hidden,false);
assert.equal(ui.q('#reflection-options').children.length,2);
ui.click('[data-reflection-answer="false"]');
ui.click('#similar-retry');
ui.similar(22);
assert.equal(ui.read().coachingRecords.at(-1).firstTry,false);
assert.equal(ui.read().coachingRecords.at(-1).independent,false);
assert.equal(ui.writes.length,0,'All parent testing leaves saved records untouched');
assert.equal(ui.w.localStorage.getItem(keys.original),JSON.stringify([legacy]));
ui.q('#practice-dialog').close();
ui.click('#start-learning-button');
assert.equal(ui.q('#continue-learning').hidden,false);
assert.equal(ui.q('#learning-clear-note').hidden,false);
ui.click('#cancel-learning');
assert.equal(ui.read().mode,'preview');
ui.click('#start-learning-button');
ui.click('#confirm-fresh');
assert.equal(ui.read().mode,'learning');
assert.equal(ui.w.location.search,'');
assert.equal(ui.read().records.length,0);
assert.equal(ui.read().coachingRecords.length,0);
assert.equal(ui.w.localStorage.getItem(keys.original),'[]');
assert.equal(ui.w.localStorage.getItem(keys.coaching),'[]');
assert.equal(ui.w.localStorage.getItem('unrelated'),'keep');
ui.open('2026-3');
assert.equal(ui.answer('D').independent,true);
ui.click('#coach-open');
ui.click('[data-coach-answer="b"]');
ui.click('#coach-next');
ui.click('[data-coach-answer="a"]');
assert.equal(ui.read().records.at(-1).independent,true,'Post-answer reasoning does not erase independent work');
ui.click('#similar-open');
ui.similar('A');
ui.click('[data-reflection-answer="a"]');
ui.q('#practice-dialog').close();
const learningSaved = ui.snapshot();
ui.click('#enter-preview-button');
assert.equal(ui.read().records.length,0);
ui.open('2026-2');
ui.click('#video-button');
ui.click('#video-recommendations button');
assert.equal(ui.answer(53).independent,false);
ui.click('#similar-open');
ui.similar(88);
ui.click('[data-reflection-answer="false"]');
assert.deepEqual(ui.snapshot(),learningSaved,'Later parent previews never overwrite saved learning');
ui.q('#practice-dialog').close();
ui.click('[data-view="papers"]');
assert.match(ui.w.location.search,/preview=1/,'Navigation preserves the safe preview URL');
ui.close();

const reload = await setup(learningSaved,'https://kmantec.github.io/AMC-Tutorial/');
assert.equal(reload.read().mode,'learning');
assert.equal(reload.read().records.length,1);
assert.equal(reload.read().records[0].problem,'2026-3');
assert.ok(reload.read().coachingRecords.length >= 4);
reload.open('2026-3');
reload.answer('D');
reload.click('#similar-open');
reload.similar('A');
assert.equal(reload.read().coachingRecords.at(-1).firstTry,false,'Reload cannot turn an already-seen adaptation into a first try');
reload.q('#practice-dialog').close();
reload.click('#reset-learning-button');
reload.click('#cancel-learning');
assert.ok(reload.read().records.length > 0);
reload.open('2026-1');
reload.click('#coach-open');
reload.w.localStorage.setItem(keys.original,'[]');
reload.w.localStorage.setItem(keys.coaching,'[]');
reload.w.dispatchEvent(new reload.w.StorageEvent('storage',{key:keys.original,newValue:'[]'}));
assert.equal(reload.read().records.length,0);
assert.equal(reload.read().coachingRecords.length,0);
assert.equal(reload.read().coachUsed,false,'A reset in another tab clears stale attempts');
assert.equal(reload.q('#coach-check').hidden,true);
reload.close();
console.log('Verified actual app DOM interactions: all three guides and adaptations, feedback, gating, isolation, video lifecycle, no-write preview, explicit fresh start, saved reload, and cross-tab reset. Layout and physical iPad playback are not simulated.');
