// Uses isolated synthetic browser storage only. No real learner records or network.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { JSDOM } from 'jsdom';
import { learningStorageKeys as keys } from './learning-store.js';
import { coachGuides } from './coach-content.js';
import { fakeSpeech, sampleVoices } from './speech-fixture.mjs';

const html = fs.readFileSync(new URL('./index.html',import.meta.url),'utf8');
const legacy = {problem:'2026-1',result:'correct',hints:0,independent:true,at:'2026-09-14T00:00:00Z'};
let scenario = 0;
async function setup(saved = {}, url = 'https://kmantec.github.io/AMC-Tutorial/?preview=1', speech = null) {
  const dom = new JSDOM(html,{url,pretendToBeVisual:true});
  const w = dom.window, registrations = new Map(), errors = [], timers = [];
  if (speech) Object.assign(w,speech.host);
  w.addEventListener('error',(event) => { errors.push(event.error || event.message); event.preventDefault(); });
  w.HTMLElement.prototype.scrollIntoView = function() {};
  w.scrollTo = () => {};
  w.HTMLDialogElement.prototype.showModal = function() { this.open = true; };
  w.HTMLDialogElement.prototype.close = function() { this.open = false; this.dispatchEvent(new w.Event('close')); };
  for (const [key,value] of Object.entries(saved)) w.localStorage.setItem(key,value);
  const writes = [], set = w.Storage.prototype.setItem;
  w.Storage.prototype.setItem = function(key,value) { writes.push([key,value]); return set.call(this,key,value); };
  w.document.modelContext = {registerTool(tool) { registrations.set(tool.name,tool); }};
  Object.assign(globalThis,{window:w,document:w.document,location:w.location,history:w.history,FormData:w.FormData});
  const realSetTimeout = globalThis.setTimeout;
  globalThis.setTimeout = (fn,delay,...args) => { const id = realSetTimeout(fn,delay,...args); timers.push(id); return id; };
  await import('./app.js?uiScenario=' + (++scenario));
  const q = (selector) => { const result = w.document.querySelector(selector); assert.ok(result,'Missing element: ' + selector); return result; };
  const click = (selector) => { q(selector).click(); assert.deepEqual(errors,[]); };
  const read = () => registrations.get('read_practice_progress').execute();
  const open = (id) => registrations.get('start_practice_problem').execute({problemId:id});
  const answer = (value) => registrations.get('submit_practice_answer').execute({answer:value});
  const similar = (value) => {
    const radio = q('#similar-options input[value="' + value + '"]');
    radio.checked = true; radio.dispatchEvent(new w.Event('change',{bubbles:true}));
    q('#similar-form').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
    assert.deepEqual(errors,[]);
  };
  return {w,q,click,read,open,answer,similar,writes,registrations,
    snapshot:() => Object.fromEntries(Object.keys(w.localStorage).map((key) => [key,w.localStorage.getItem(key)])),
    close:() => { for (const id of timers) clearTimeout(id); globalThis.setTimeout = realSetTimeout; dom.window.close(); }};
}
const ui = await setup({[keys.original]:JSON.stringify([legacy]),[keys.mode]:'learning',unrelated:'keep'});
assert.equal(ui.read().mode,'preview');
assert.deepEqual(ui.read().records,[]);
assert.equal(ui.writes.length,0);
assert.equal(ui.q('#coach-listen').disabled,true,'Unsupported speech leaves the original learning flow usable');
assert.match(ui.q('#coach-voice-status').textContent,/unavailable/);
ui.open('2026-1');
assert.equal(ui.q('#coach-check').hidden,true,'No targeted coaching before a request');
assert.equal(ui.q('#similar-entry').hidden,true);
assert.equal(ui.q('#coach-options').children.length,0);
ui.answer(21);
ui.click('#coach-open');
assert.equal(ui.read().coachUsed,true);
assert.equal(ui.q('#coach-options').children.length,2);
const first = coachGuides['2026-1'].checks[0];
ui.click('[data-coach-answer="' + first.options.find((option) => !option.correct).id + '"]');
const length = ui.read().coachingRecords.length;
ui.click('[data-coach-answer="' + first.options.find((option) => option.correct).id + '"]');
assert.equal(ui.read().coachingRecords.length,length,'Disabled choices do not overwrite the first response');
assert.equal(ui.read().coachingRecords.at(-1).correct,false);
ui.click('#coach-next');
ui.click('[data-coach-answer="a"]');
ui.q('#practice-dialog').close();
ui.open('2026-2');
assert.equal(ui.q('#coach-check').hidden,true);
assert.equal(ui.q('#suggested-pace').textContent,'Suggested pace: within 1 min 30 sec');
assert.equal(ui.answer(53).independent,true,'Q1 assistance does not affect Q2');
const beforeVideo = ui.read().records.length;
ui.click('#video-button');
ui.click('#video-recommendations button');
assert.ok(ui.w.document.querySelector('#video-player iframe'));
assert.equal(ui.read().records.length,beforeVideo,'Post-answer video does not change the completed result');
ui.open('2026-1');
assert.equal(ui.w.document.querySelector('#video-player iframe'),null);
assert.equal(ui.q('#coach-check').hidden,false);
assert.match(ui.q('#coach-step').textContent,/2 OF 2/);
assert.equal(ui.answer(18).independent,false);
const originals = ui.read().records.length;
ui.click('#similar-open');
assert.equal(ui.q('#similar-options').querySelectorAll('input').length,2);
assert.equal(ui.q('#similar-explanation').hidden,true);
assert.equal(ui.q('#reflection-options').children.length,0);
ui.similar(26);
assert.equal(ui.read().records.length,originals,'Adapted results do not count as AMC attempts');
assert.equal(ui.read().coachingRecords.at(-1).kind,'similar');
assert.equal(ui.read().coachingRecords.at(-1).correct,false);
assert.equal(ui.q('#similar-explanation').hidden,false);
assert.equal(ui.q('#reflection-options').children.length,2);
ui.click('[data-reflection-answer="false"]');
ui.click('#similar-retry');
ui.similar(22);
assert.equal(ui.read().coachingRecords.at(-1).firstTry,false);
assert.equal(ui.read().coachingRecords.at(-1).independent,false);
assert.equal(ui.writes.length,0,'All parent testing leaves saved records untouched');
assert.equal(ui.w.localStorage.getItem(keys.original),JSON.stringify([legacy]));
ui.q('#practice-dialog').close();
ui.click('#start-learning-button');
assert.equal(ui.q('#continue-learning').hidden,false);
assert.equal(ui.q('#learning-clear-note').hidden,false);
ui.click('#cancel-learning');
assert.equal(ui.read().mode,'preview');
ui.click('#start-learning-button');
ui.click('#confirm-fresh');
assert.equal(ui.read().mode,'learning');
assert.equal(ui.w.location.search,'');
assert.equal(ui.read().records.length,0);
assert.equal(ui.read().coachingRecords.length,0);
assert.equal(ui.w.localStorage.getItem(keys.original),'[]');
assert.equal(ui.w.localStorage.getItem(keys.coaching),'[]');
assert.equal(ui.w.localStorage.getItem('unrelated'),'keep');
ui.open('2026-3');
assert.equal(ui.answer('D').independent,true);
ui.click('#coach-open');
ui.click('[data-coach-answer="b"]');
ui.click('#coach-next');
ui.click('[data-coach-answer="a"]');
assert.equal(ui.read().records.at(-1).independent,true,'Post-answer reasoning does not erase independent work');
ui.click('#similar-open');
ui.similar('A');
ui.click('[data-reflection-answer="a"]');
ui.q('#practice-dialog').close();
const learningSaved = ui.snapshot();
ui.click('#enter-preview-button');
assert.equal(ui.read().records.length,0);
ui.open('2026-2');
ui.click('#video-button');
ui.click('#video-recommendations button');
assert.equal(ui.answer(53).independent,false);
ui.click('#similar-open');
ui.similar(88);
ui.click('[data-reflection-answer="false"]');
assert.deepEqual(ui.snapshot(),learningSaved,'Later parent previews never overwrite saved learning');
ui.q('#practice-dialog').close();
ui.click('[data-view="papers"]');
assert.match(ui.w.location.search,/preview=1/,'Navigation preserves the safe preview URL');
ui.close();

const reload = await setup(learningSaved,'https://kmantec.github.io/AMC-Tutorial/');
assert.equal(reload.read().mode,'learning');
assert.equal(reload.read().records.length,1);
assert.equal(reload.read().records[0].problem,'2026-3');
assert.ok(reload.read().coachingRecords.length >= 4);
reload.open('2026-3');
reload.answer('D');
reload.click('#similar-open');
reload.similar('A');
assert.equal(reload.read().coachingRecords.at(-1).firstTry,false,'Reload cannot turn an already-seen adaptation into a first try');
reload.q('#practice-dialog').close();
reload.click('#reset-learning-button');
reload.click('#cancel-learning');
assert.ok(reload.read().records.length > 0);
reload.open('2026-1');
reload.click('#coach-open');
reload.w.localStorage.setItem(keys.original,'[]');
reload.w.localStorage.setItem(keys.coaching,'[]');
reload.w.dispatchEvent(new reload.w.StorageEvent('storage',{key:keys.original,newValue:'[]'}));
assert.equal(reload.read().records.length,0);
assert.equal(reload.read().coachingRecords.length,0);
assert.equal(reload.read().coachUsed,false,'A reset in another tab clears stale attempts');
assert.equal(reload.q('#coach-check').hidden,true);
reload.close();
const voice = fakeSpeech();
const audioUI = await setup({},'https://kmantec.github.io/AMC-Tutorial/?preview=1',voice);
assert.equal(voice.calls.length,0,'Page load must remain silent');
audioUI.open('2026-1');
assert.equal(voice.calls.length,0,'Opening the original problem must remain silent');
audioUI.click('#solution-listen');
assert.equal(voice.calls.length,0,'A hidden solution cannot be read through its handler');
audioUI.click('#coach-listen');
assert.match(voice.text,/Try a first step on paper/);
assert.equal(audioUI.read().records.length,0,'Reading a non-spoiling intro earns no assistance event');
audioUI.click('#coach-stop');
audioUI.click('#coach-open');
assert.match(voice.text,/Which way of adding brackets/);
assert.match(voice.text,/First choice/);
assert.match(voice.text,/Second choice/);
assert.doesNotMatch(voice.text,/Opening these brackets gives exactly/,'Unchosen feedback must not be spoken');
const speechCount = voice.calls.length;
voice.changeVoices(sampleVoices);
assert.equal(audioUI.q('#coach-voice').options.length,4,'Late voice discovery updates the picker');
assert.equal(voice.calls.length,speechCount,'Voice discovery must not autoplay');
const britishOption = [...audioUI.q('#coach-voice').options].find((option) => /en-GB/.test(option.textContent));
audioUI.q('#coach-voice').value = britishOption.value;
audioUI.q('#coach-voice').dispatchEvent(new audioUI.w.Event('change',{bubbles:true}));
assert.equal(voice.pending.length,0);
audioUI.click('#coach-listen');
assert.equal(voice.pending[0].voice.lang,'en-GB');
audioUI.click('[data-coach-answer="a"]');
assert.match(voice.text,/That minus sign changes/);
audioUI.click('#coach-mute');
assert.equal(voice.pending.length,0,'Mute immediately cancels all queued parts');
assert.equal(audioUI.q('#coach-mute').getAttribute('aria-pressed'),'true');
assert.equal(audioUI.q('#coach-listen').disabled,true);
const whileMuted = voice.calls.length;
const beforeControls = JSON.stringify(audioUI.read().records);
audioUI.click('#coach-next');
assert.equal(voice.calls.length,whileMuted,'Next-step actions respect mute');
audioUI.click('#coach-mute');
assert.equal(voice.calls.length,whileMuted,'Unmute alone does not replay stale speech');
audioUI.click('#coach-listen');
assert.match(voice.text,/Why can we add the block totals/);
assert.equal(JSON.stringify(audioUI.read().records),beforeControls,'Voice controls never create learner events');
audioUI.answer(18);
assert.equal(voice.pending.length,0,'Checking the original answer stops earlier coaching');
audioUI.click('#solution-listen');
assert.match(voice.text,/Add the four block totals/);
audioUI.click('#similar-open');
assert.match(voice.text,/not an official AMC question/);
assert.doesNotMatch(voice.text,/Add the block totals/,'Adapted answer steps stay silent before a response');
assert.doesNotMatch(voice.text,/moving minus 7 to a different group/,'Adapted reflection stays silent before a response');
audioUI.similar(22);
assert.match(voice.text,/Add the block totals/);
assert.match(voice.text,/True or false/);
audioUI.click('[data-reflection-answer="false"]');
assert.match(voice.text,/Keep minus 7 as minus 7/);
audioUI.click('#next-problem');
assert.equal(voice.pending.length,0,'Switching problems stops all old narration');
audioUI.click('#coach-listen');
assert.match(voice.text,/There are many entries here/);
assert.doesNotMatch(voice.text,/minus 7/);
audioUI.click('#video-button');
assert.equal(voice.pending.length,0,'Opening a video stops speech');
audioUI.click('#video-recommendations button');
assert.ok(audioUI.q('#video-player').children.length);
audioUI.click('#coach-listen');
assert.equal(audioUI.q('#video-player').children.length,0,'Speech replay stops the embedded video');
voice.fail('not-allowed');
assert.match(audioUI.q('#coach-voice-status').textContent,/Tap Listen again/);
audioUI.click('#coach-listen');
let background = true;
Object.defineProperty(audioUI.w.document,'hidden',{configurable:true,get:() => background});
audioUI.w.document.dispatchEvent(new audioUI.w.Event('visibilitychange'));
assert.equal(voice.pending.length,0,'Backgrounding stops the voice');
const beforeReturn = voice.calls.length;
background = false;
audioUI.w.document.dispatchEvent(new audioUI.w.Event('visibilitychange'));
assert.equal(voice.calls.length,beforeReturn,'Returning to the page does not autoplay');
audioUI.click('#coach-listen');
audioUI.w.dispatchEvent(new audioUI.w.Event('pagehide'));
assert.equal(voice.pending.length,0);
audioUI.click('#coach-listen');
audioUI.q('#practice-dialog').close();
assert.equal(voice.pending.length,0,'Closing practice stops the voice');
assert.equal(audioUI.writes.length,0,'Speech preferences and all preview tests must not write storage');
audioUI.click('#start-learning-button');
audioUI.click('#confirm-fresh');
audioUI.open('2026-3');
audioUI.click('#coach-open');
assert.match(voice.text,/how much wire/);
audioUI.w.localStorage.setItem(keys.original,'[]');
audioUI.w.dispatchEvent(new audioUI.w.StorageEvent('storage',{key:keys.original,newValue:'[]'}));
assert.equal(voice.pending.length,0,'Cross-tab reset stops stale speech');
audioUI.click('#coach-listen');
assert.match(voice.text,/Take the shapes one at a time/);
audioUI.close();
console.log('Verified speech UI with a simulated engine: voice picker, mute/replay, spoiler gates, no progress writes, and cancellation on navigation, video, background, close, and reset. Actual device audio is not simulated.');

const fourthVoice = fakeSpeech(sampleVoices);
const priorRecords = [
  legacy,
  {...legacy,problem:'2026-2',independent:false},
  {...legacy,problem:'2026-3'},
];
const priorSaved = {[keys.original]:JSON.stringify(priorRecords),[keys.mode]:'learning'};
const fourthUI = await setup(priorSaved,'https://kmantec.github.io/AMC-Tutorial/?preview=1&problem=2026-4',fourthVoice);
assert.equal(fourthUI.read().activeProblem,'2026-4','A direct review link opens the new question');
assert.equal(fourthUI.read().practiceOpen,true);
assert.equal(fourthUI.read().reviewedProblemsAvailable,5);
assert.equal(fourthUI.read().mode,'preview');
assert.equal(fourthVoice.calls.length,0,'Opening a direct problem link never autoplays');
assert.equal(fourthUI.q('#next-problem').disabled,false);
assert.equal(fourthUI.q('#problem-data').hidden,true,'A prose-only problem needs no empty data panel');
assert.equal(fourthUI.q('#wording-note').hidden,false);
assert.deepEqual([...fourthUI.w.document.querySelectorAll('#answer-options input')].map((input) => input.value),['80','90','100','110','120']);
assert.equal(fourthUI.q('#checked-source').href,'https://live.poshenloh.com/past-contests/amc8/2026/problem/4');
assert.equal(fourthUI.q('#video-button').hidden,false);
assert.equal(fourthUI.q('#video-unavailable').hidden,true);
assert.equal(fourthUI.w.document.querySelector('#video-player iframe'),null,'A direct problem link never loads a video');
assert.throws(() => fourthUI.registrations.get('open_recommended_walkthrough').execute({videoId:'unavailable'}),/Choose an available/);
assert.equal(fourthUI.read().videoUsed,false,'An unavailable video cannot add a support event');
fourthUI.click('#video-button');
assert.match(fourthUI.q('#video-recommendations').textContent,/PARENT’S SELECTION/);
assert.match(fourthUI.q('#video-recommendations').textContent,/Coach review is still pending/);
assert.doesNotMatch(fourthUI.q('#video-recommendations').textContent,/120|COACH’S PICK/,'The card gives neither the answer nor an unearned recommendation');
fourthUI.click('#video-recommendations button');
const fourthEmbed = new URL(fourthUI.q('#video-player iframe').src);
assert.equal(fourthEmbed.origin,'https://www.youtube-nocookie.com');
assert.equal(fourthEmbed.pathname,'/embed/gzXlOkLl24U');
assert.equal(fourthEmbed.searchParams.get('start'),'141');
assert.equal(fourthEmbed.searchParams.get('end'),'186');
assert.equal(fourthEmbed.searchParams.get('autoplay'),'0');
assert.equal(fourthUI.q('#youtube-fallback').href,'https://www.youtube.com/watch?v=gzXlOkLl24U&t=141s');
assert.equal(fourthUI.read().videoUsed,true);
assert.equal(fourthUI.read().records.at(-1).result,'video');
fourthUI.click('#back-to-problem');
assert.equal(fourthUI.w.document.querySelector('#video-player iframe'),null);
assert.equal(fourthUI.answer(120).independent,false,'Parent-selected videos also count as support');
fourthUI.click('#retry-button');
fourthUI.click('#coach-open');
assert.match(fourthVoice.text,/50 percent/);
fourthUI.click('[data-coach-answer="a"]');
assert.match(fourthVoice.text,/80 units remaining/);
fourthUI.click('#coach-next');
fourthUI.click('[data-coach-answer="b"]');
assert.match(fourthVoice.text,/extra savings/);
fourthUI.click('#previous-problem');
assert.equal(fourthUI.read().activeProblem,'2026-3');
assert.equal(fourthVoice.pending.length,0);
assert.equal(fourthUI.q('#problem-data').hidden,false);
assert.equal(fourthUI.q('#checked-source').hidden,true);
assert.equal(fourthUI.q('#video-button').hidden,false);
assert.equal(fourthUI.q('#video-unavailable').hidden,true);
fourthUI.click('#next-problem');
assert.equal(fourthUI.q('#coach-check').hidden,false,'The new problem preserves its own coaching state');
assert.equal(fourthUI.q('#problem-data').hidden,true);
assert.equal(fourthUI.answer(120).independent,false);
fourthUI.click('#similar-open');
assert.equal(fourthUI.q('#similar-data').hidden,true);
assert.match(fourthVoice.text,/25 percent/);
assert.doesNotMatch(fourthVoice.text,/75 units/,'The new adaptation is not explained before a response');
fourthUI.similar(95);
assert.equal(fourthUI.read().coachingRecords.at(-1).correct,false);
assert.match(fourthVoice.text,/20 percent of 75/);
fourthUI.click('[data-reflection-answer="false"]');
fourthUI.click('#similar-retry');
fourthUI.similar(90);
assert.equal(fourthUI.read().coachingRecords.at(-1).firstTry,false);
fourthUI.click('[data-reflection-answer="true"]');
assert.equal(fourthUI.read().coachingRecords.at(-1).correct,true);
assert.equal(fourthUI.read().coachingRecords.at(-1).firstTry,false);
assert.equal(fourthUI.writes.length,0);
assert.deepEqual(fourthUI.snapshot(),priorSaved,'Previewing Problem 4 preserves earlier learner records');
fourthUI.close();

const fourthLearning = await setup(priorSaved,'https://kmantec.github.io/AMC-Tutorial/?problem=2026-4');
assert.equal(fourthLearning.read().records.length,3);
assert.equal(fourthLearning.q('#completed-count').textContent,'3');
assert.equal(fourthLearning.answer(110).correct,false);
assert.equal(fourthLearning.answer(120).independent,false);
fourthLearning.click('#retry-button');
assert.equal(fourthLearning.answer(120).independent,true);
const completedFourthRecords = fourthLearning.read().records.length;
fourthLearning.click('#video-button');
fourthLearning.click('#video-recommendations button');
assert.equal(fourthLearning.read().records.length,completedFourthRecords,'Post-answer Q4 video preserves independent credit');
fourthLearning.click('#previous-problem');
assert.equal(fourthLearning.w.document.querySelector('#video-player iframe'),null,'Switching away from Q4 removes its player');
assert.match(fourthLearning.q('#video-recommendations').textContent,/COACH’S PICK/,'Q3 retains its reviewed recommendation');
fourthLearning.click('#next-problem');
assert.equal(fourthLearning.q('#completed-count').textContent,'4');
assert.equal(fourthLearning.q('#independent-count').textContent,'3');
assert.deepEqual(fourthLearning.read().records.slice(0,3),priorRecords,'New original attempts append to existing history');
assert.equal(fourthLearning.read().coachingRecords.length,0,'Preview coach records are not imported into saved learning');
const savedFour = fourthLearning.snapshot();
fourthLearning.close();
const fourReload = await setup(savedFour,'https://kmantec.github.io/AMC-Tutorial/?problem=2026-4');
assert.equal(fourReload.q('#completed-count').textContent,'4');
assert.equal(fourReload.read().submitted,false,'Reload starts a fresh attempt but retains saved history');
assert.equal(fourReload.writes.length,0);
fourReload.close();
console.log('Verified Problem 4: direct preview, original choices, prose-only rendering, source links, parent-selected video bounds/support, percent speech, both coach paths, adaptation/revisit, and legacy progress across reload.');


// Problem 5 adds content without changing the approved design or old records.
const priorFour = [...priorRecords,{...legacy,problem:'2026-4'}];
const savedBeforeFive = {[keys.original]:JSON.stringify(priorFour),[keys.mode]:'learning',unrelated:'keep'};
const fifthVoice = fakeSpeech(sampleVoices);
const fifthUI = await setup(savedBeforeFive,'https://kmantec.github.io/AMC-Tutorial/?preview=1&problem=2026-5',fifthVoice);
assert.equal(fifthUI.read().activeProblem,'2026-5');
assert.equal(fifthUI.read().reviewedProblemsAvailable,5);
assert.equal(fifthUI.read().mode,'preview');
assert.equal(fifthUI.q('#next-problem').disabled,true);
assert.equal(fifthUI.q('#previous-problem').disabled,false);
assert.equal(fifthUI.q('#problem-data').hidden,true);
assert.equal(fifthUI.q('#wording-note').hidden,false);
assert.deepEqual([...fifthUI.w.document.querySelectorAll('#answer-options input')].map(input => input.value),['15','30','40','45','60']);
assert.equal(fifthUI.q('#checked-source').href,'https://live.poshenloh.com/past-contests/amc8/2026/problem/5');
assert.equal(fifthUI.q('#suggested-pace').textContent,'Suggested pace: within 1 min 30 sec');
assert.equal(fifthVoice.calls.length,0);
assert.equal(fifthUI.q('#video-button').hidden,true);
assert.equal(fifthUI.q('#video-unavailable').hidden,false);
assert.match(fifthUI.q('#video-unavailable').textContent,/not available/);
assert.throws(() => fifthUI.registrations.get('open_recommended_walkthrough').execute({videoId:'gzXlOkLl24U'}),/Choose an available/);
assert.equal(fifthUI.read().videoUsed,false,'Q4 video cannot be used as an unreviewed Q5 recommendation');
assert.equal(fifthUI.q('#similar-entry').hidden,true);
assert.equal(fifthUI.answer(45).correct,false);
assert.equal(fifthUI.answer(30).independent,false,'A wrong Q5 answer removes independent credit for that attempt');
fifthUI.click('#retry-button');
fifthUI.click('#coach-open');
assert.match(fifthVoice.text,/40 miles per hour/);
assert.doesNotMatch(fifthVoice.text,/2\.5|30 minutes/,'The first guided check does not speak the unrevealed calculation');
fifthUI.click('[data-coach-answer="b"]');
assert.equal(fifthUI.read().coachingRecords.at(-1).correct,false);
fifthUI.click('#coach-next');
fifthUI.click('[data-coach-answer="a"]');
assert.match(fifthVoice.text,/half of 60 is 30/);
fifthUI.click('#previous-problem');
assert.equal(fifthUI.read().activeProblem,'2026-4');
assert.equal(fifthVoice.pending.length,0);
assert.equal(fifthUI.q('#video-button').hidden,false);
assert.equal(fifthUI.q('#coach-check').hidden,true,'Q5 guidance stays separate from Q4');
assert.equal(fifthUI.answer(120).independent,true);
fifthUI.click('#next-problem');
assert.equal(fifthUI.q('#coach-check').hidden,false);
assert.equal(fifthUI.q('#video-button').hidden,true);
assert.equal(fifthUI.answer(30).independent,false,'Q5 guided checks count as support');
const fifthOriginalEvents = fifthUI.read().records.length;
fifthUI.click('#similar-open');
assert.equal(fifthUI.q('#similar-data').hidden,true);
assert.match(fifthVoice.text,/150 miles/);
assert.doesNotMatch(fifthVoice.text,/195|0\.75/,'The adapted solution is not spoken before answering');
fifthUI.similar(75);
assert.equal(fifthUI.read().coachingRecords.at(-1).correct,false);
assert.match(fifthVoice.text,/195 minus 150 equals 45/);
fifthUI.click('[data-reflection-answer="true"]');
assert.equal(fifthUI.read().coachingRecords.at(-1).correct,false);
fifthUI.click('#similar-retry');
fifthUI.similar(45);
assert.equal(fifthUI.read().coachingRecords.at(-1).correct,true);
assert.equal(fifthUI.read().coachingRecords.at(-1).firstTry,false);
fifthUI.click('[data-reflection-answer="false"]');
assert.equal(fifthUI.read().coachingRecords.at(-1).correct,true);
assert.equal(fifthUI.read().records.length,fifthOriginalEvents,'Adapted Q5 does not add original-exam progress');
assert.equal(fifthUI.writes.length,0);
assert.deepEqual(fifthUI.snapshot(),savedBeforeFive,'Q5 preview preserves all earlier saved records and unrelated storage');
fifthUI.close();

const fifthLearning = await setup(savedBeforeFive,'https://kmantec.github.io/AMC-Tutorial/?problem=2026-5');
assert.equal(fifthLearning.q('#completed-count').textContent,'4');
assert.equal(fifthLearning.answer(30).independent,true);
assert.equal(fifthLearning.q('#completed-count').textContent,'5');
assert.equal(fifthLearning.q('#independent-count').textContent,'4');
assert.deepEqual(fifthLearning.read().records.slice(0,4),priorFour);
fifthLearning.click('#similar-open');
fifthLearning.similar(45);
assert.equal(fifthLearning.read().coachingRecords.at(-1).firstTry,true);
fifthLearning.click('[data-reflection-answer="false"]');
const savedFive = fifthLearning.snapshot();
fifthLearning.close();
const fifthReload = await setup(savedFive,'https://kmantec.github.io/AMC-Tutorial/?problem=2026-5');
assert.equal(fifthReload.q('#completed-count').textContent,'5');
assert.equal(fifthReload.read().submitted,false);
assert.equal(fifthReload.writes.length,0);
fifthReload.click('#reveal-button');
fifthReload.click('#similar-open');
fifthReload.similar(45);
assert.equal(fifthReload.read().coachingRecords.at(-1).firstTry,false,'Saved exposure to Q5 adaptation survives a reload');
assert.equal(fifthReload.read().coachingRecords.at(-1).independent,false);
assert.equal(fifthReload.snapshot().unrelated,'keep');
fifthReload.close();
console.log('Verified Problem 5: choices, rates/units, guided checks, adaptation/revisit, speech gates, missing-video notice, preview isolation, and saved Q1–Q4 history.');

console.log('Verified actual app DOM interactions: all five guides and adaptations, feedback, gating, isolation, video lifecycle, no-write preview, explicit fresh start, saved reload, and cross-tab reset. Layout and physical iPad playback are not simulated.');
